import ReactDOM  from "react-dom/client";
//import Ten from "./ten";
//import Count from "./classComponentcount";
// import Eight from "./eight";
//import { useRef } from "react";
//import { Assign } from "./assignment";
//import Ele from "../src/Useref";
//import Login from "./login";
//import Tab from "./tabshift";
//import Details from "./details";
//import Reg from "./details2";
import DataFetching from "./datafetching";
//import Practice from "./practice";
//import CardListUI from "./CardList";
//import Likitha from "./likithalist";
//import DataFetching2 from "./product";
import DataFetching3 from "./fetching3.js";
import App from "./App.js";
const rootElement = document.getElementById('root');
const rootRef = ReactDOM.createRoot(rootElement);
rootRef.render(<App/>);